
export const UPDATE_INPUT_PAGEBAR = "UPDATE_INPUT_PAGEBAR" ;
export const QUERYLIST_FOR_PAGE = "QUERYLIST_FOR_PAGE" ;
export const UPDATE_SIMPLE_STATE= "UPDATE_SIMPLE_STATE" ;//简单更新state数据

export const ORDER_LISTDATA = "ORDER_LISTDATA" ; //orderListData
export const UPDATE_TABLETITLE_ORDER = "UPDATE_TABLETITLE_ORDER" ;
export const CLEAR_TABLETITLE_ORDERINFO = "CLEAR_TABLETITLE_ORDERINFO" ;
export const defaultOrderFlag = true ;
export const UPDATE_FORMDATA_ARRAY = "UPDATE_FORMDATA_ARRAY"  ;
export const UPDATE_FORMDATA_SIMPLE = "UPDATE_FORMDATA_SIMPLE"  ;
//单个checkbox被点击时更新数据
export const UPDATE_SINGLE_CHECKEDIDARR = "UPDATE_SINGLE_CHECKEDIDARR" ;
//全选checkbox被单击时更新数据
export const UPDATE_ALL_CHECKEDIDARR = "UPDATE_ALL_CHECKEDIDARR" ;
export const BATCH_DELETE_RECORDS7 = "BATCH_DELETE_RECORDS7" ;
export const BATCH_ABORT_RECORDS7 = "BATCH_ABORT_RECORDS7" ;//batchAbortRecords7